### ISSUE TITLE
Application error on Heroku

### ISSUE THREAD

**Issue by RhodesPeter** [FAC10/week-6-jajascript#47]
Your project is currently not running on Heroku:

![screen shot 2017-03-31 at 10 03 53](https://cloud.githubusercontent.com/assets/18164707/24543964/67e2daba-15f9-11e7-981b-958cafb593f0.png)

**Comment by RhodesPeter** [comment]
I will be happy to help you later if you have any issues with heroku 😀

**Comment by joeylouise** [comment]
Thanks, @RhodesPeter, we hadn't added our config.env to Heroku and also had to have pg as a dependency and not a dev dependency
#68 fixes this

**Comment by RhodesPeter** [comment]
Great :)
