### ISSUE TITLE
Tests are not ending

### ISSUE THREAD

**Issue by RhodesPeter** [FAC10/week-6-jajascript#57]
I don't think your tests are ending.

I have to press `control + C` to break out of `npm test`. 

Do you have `t.end();` on all your tests? 

Could this be happening for another reason?

**Comment by RhodesPeter** [comment]
You should get a report at the end like this:

![screen shot 2017-03-31 at 10 36 09](https://cloud.githubusercontent.com/assets/18164707/24545130/e28aba68-15fd-11e7-9549-ab3b94b13bd3.png)

**Comment by joeylouise** [comment]
Thanks, @RhodesPeter  - the tests do end but they take some time! We've added documentation to our README and tests to let users know that it takes a bit longer

**Comment by antoniotrkdz** [comment]
I have added a sentence tho each test title to warn the tester that the test will take some time.
