### ISSUE TITLE
Scrappy tests.js file

### ISSUE THREAD

**Issue by RhodesPeter** [FAC10/week-6-jajascript#59]
Please could you remove commented out code and any unneeded comments?

![screen shot 2017-03-31 at 10 32 26](https://cloud.githubusercontent.com/assets/18164707/24545026/7e4e6f9a-15fd-11e7-83cb-7058700ae4e0.png)

Also `const setData = require('../../src/setData.js');` is not currently being used. As it was in code that is commented out, if you remove the commented out test please remove this too.

**Comment by antoniotrkdz** [comment]
Removed, thanks!
