### ISSUE TITLE
Declaring variables without keyword

### ISSUE THREAD

**Issue by RhodesPeter** [FAC10/week-6-jajascript#61]
It's best practice to always declare variables with a variable keyword (var, let, const).

In dynamic.js you have declared `data` without a keyword, it should be `let data = {};` or `const data = {};`

![screen shot 2017-03-31 at 10 39 17](https://cloud.githubusercontent.com/assets/18164707/24545330/ad5d692a-15fe-11e7-9a38-9baf73c6461a.png)

More infomation [here](http://stackoverflow.com/questions/6888570/declaring-variables-without-var-keyword).

**Comment by jessicasalmon** [comment]
Thank you, done :)
